// Copies the kit's drawing code into a TS module the Remotion composition can evaluate.
// Run after updating files in ./kids-kit:  npm run sync-kit
import {readFileSync, writeFileSync} from 'node:fs';

const read = (f) => readFileSync(new URL(`../kids-kit/${f}`, import.meta.url), 'utf8');
const tpl = read('comp_template.html');
// engine = template script between the TAU constant and the SHOT LIST (word clock, BEAT, captions, wipe)
const script = tpl.slice(tpl.indexOf('<script>') + 8, tpl.indexOf('</script>'));
const preamble = script.slice(script.indexOf('const DISPLAY'), script.indexOf('/*PRIMS*/'));
const engine = script.slice(script.indexOf('/* ---------- word clock'), script.indexOf('/* ====='));

const out = `// GENERATED by scripts/sync-kit.mjs from ./kids-kit. Do not edit by hand.
export const KIT_PREAMBLE = ${JSON.stringify(preamble)};
export const KIT_PRIMS = ${JSON.stringify(read('prims.js'))};
export const KIT_PROPS = ${JSON.stringify(read('props.js'))};
export const KIT_CHARS = ${JSON.stringify(read('characters.js'))};
export const KIT_ENGINE = ${JSON.stringify(engine)};
`;
writeFileSync(new URL('../src/remotion/kids/kit-source.ts', import.meta.url), out);
console.log('kit-source.ts written');
